// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * --- новый метод ---
 * @returns {$CancellablePromise<void>}
 */
export function SetTaskbarCompleteAndFlash() {
    return $Call.ByID(2692748932);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function SetTaskbarError() {
    return $Call.ByID(2209072648);
}

/**
 * @param {number} completed
 * @param {number} total
 * @returns {$CancellablePromise<void>}
 */
export function SetTaskbarPaused(completed, total) {
    return $Call.ByID(3050218068, completed, total);
}

/**
 * @param {number} completed
 * @param {number} total
 * @returns {$CancellablePromise<void>}
 */
export function SetTaskbarProgress(completed, total) {
    return $Call.ByID(2412174097, completed, total);
}
