// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ColorLiteral {
    /**
     * Creates a new ColorLiteral instance.
     * @param {Partial<ColorLiteral>} [$$source = {}] - The source object to create the ColorLiteral.
     */
    constructor($$source = {}) {
        if (!("space" in $$source)) {
            /**
             * "srgb"
             * @member
             * @type {string}
             */
            this["space"] = "";
        }
        if (!("r" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["r"] = 0;
        }
        if (!("g" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["g"] = 0;
        }
        if (!("b" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["b"] = 0;
        }
        if (!("a" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["a"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColorLiteral instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ColorLiteral}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColorLiteral(/** @type {Partial<ColorLiteral>} */($$parsedSource));
    }
}

export class ComponentStyle {
    /**
     * Creates a new ComponentStyle instance.
     * @param {Partial<ComponentStyle>} [$$source = {}] - The source object to create the ComponentStyle.
     */
    constructor($$source = {}) {
        if (!("component" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["component"] = "";
        }
        if (!("slots" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: { [_ in string]?: TokenValue } }}
             */
            this["slots"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ComponentStyle instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ComponentStyle}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("slots" in $$parsedSource) {
            $$parsedSource["slots"] = $$createField1_0($$parsedSource["slots"]);
        }
        return new ComponentStyle(/** @type {Partial<ComponentStyle>} */($$parsedSource));
    }
}

export class Derived {
    /**
     * Creates a new Derived instance.
     * @param {Partial<Derived>} [$$source = {}] - The source object to create the Derived.
     */
    constructor($$source = {}) {
        if (!("op" in $$source)) {
            /**
             * lighten, darken, alpha
             * @member
             * @type {string}
             */
            this["op"] = "";
        }
        if (!("from" in $$source)) {
            /**
             * @member
             * @type {TokenValue}
             */
            this["from"] = (new TokenValue());
        }
        if (!("amount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["amount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Derived instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Derived}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("from" in $$parsedSource) {
            $$parsedSource["from"] = $$createField1_0($$parsedSource["from"]);
        }
        return new Derived(/** @type {Partial<Derived>} */($$parsedSource));
    }
}

export class GradientLiteral {
    /**
     * Creates a new GradientLiteral instance.
     * @param {Partial<GradientLiteral>} [$$source = {}] - The source object to create the GradientLiteral.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * linear, radial
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["angle"] = undefined;
        }
        if (!("stops" in $$source)) {
            /**
             * @member
             * @type {GradientStop[]}
             */
            this["stops"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GradientLiteral instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GradientLiteral}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stops" in $$parsedSource) {
            $$parsedSource["stops"] = $$createField2_0($$parsedSource["stops"]);
        }
        return new GradientLiteral(/** @type {Partial<GradientLiteral>} */($$parsedSource));
    }
}

export class GradientStop {
    /**
     * Creates a new GradientStop instance.
     * @param {Partial<GradientStop>} [$$source = {}] - The source object to create the GradientStop.
     */
    constructor($$source = {}) {
        if (!("pos" in $$source)) {
            /**
             * 0..1
             * @member
             * @type {number}
             */
            this["pos"] = 0;
        }
        if (!("color" in $$source)) {
            /**
             * @member
             * @type {TokenValue}
             */
            this["color"] = (new TokenValue());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GradientStop instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GradientStop}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("color" in $$parsedSource) {
            $$parsedSource["color"] = $$createField1_0($$parsedSource["color"]);
        }
        return new GradientStop(/** @type {Partial<GradientStop>} */($$parsedSource));
    }
}

export class Literal {
    /**
     * Creates a new Literal instance.
     * @param {Partial<Literal>} [$$source = {}] - The source object to create the Literal.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ColorLiteral | null | undefined}
             */
            this["color"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {NumberLiteral | null | undefined}
             */
            this["number"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ShadowLayer[] | undefined}
             */
            this["shadow"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {GradientLiteral | null | undefined}
             */
            this["gradient"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Literal instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Literal}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType6;
        const $$createField1_0 = $$createType8;
        const $$createField2_0 = $$createType10;
        const $$createField3_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("color" in $$parsedSource) {
            $$parsedSource["color"] = $$createField0_0($$parsedSource["color"]);
        }
        if ("number" in $$parsedSource) {
            $$parsedSource["number"] = $$createField1_0($$parsedSource["number"]);
        }
        if ("shadow" in $$parsedSource) {
            $$parsedSource["shadow"] = $$createField2_0($$parsedSource["shadow"]);
        }
        if ("gradient" in $$parsedSource) {
            $$parsedSource["gradient"] = $$createField3_0($$parsedSource["gradient"]);
        }
        return new Literal(/** @type {Partial<Literal>} */($$parsedSource));
    }
}

export class NumberLiteral {
    /**
     * Creates a new NumberLiteral instance.
     * @param {Partial<NumberLiteral>} [$$source = {}] - The source object to create the NumberLiteral.
     */
    constructor($$source = {}) {
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["value"] = 0;
        }
        if (!("unit" in $$source)) {
            /**
             * px, rem, em, %
             * @member
             * @type {string}
             */
            this["unit"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NumberLiteral instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NumberLiteral}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NumberLiteral(/** @type {Partial<NumberLiteral>} */($$parsedSource));
    }
}

export class Ref {
    /**
     * Creates a new Ref instance.
     * @param {Partial<Ref>} [$$source = {}] - The source object to create the Ref.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Ref instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Ref}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Ref(/** @type {Partial<Ref>} */($$parsedSource));
    }
}

export class ResolvedTheme {
    /**
     * Creates a new ResolvedTheme instance.
     * @param {Partial<ResolvedTheme>} [$$source = {}] - The source object to create the ResolvedTheme.
     */
    constructor($$source = {}) {
        if (!("Tokens" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: ResolvedToken }}
             */
            this["Tokens"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResolvedTheme instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ResolvedTheme}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Tokens" in $$parsedSource) {
            $$parsedSource["Tokens"] = $$createField0_0($$parsedSource["Tokens"]);
        }
        return new ResolvedTheme(/** @type {Partial<ResolvedTheme>} */($$parsedSource));
    }
}

export class ResolvedToken {
    /**
     * Creates a new ResolvedToken instance.
     * @param {Partial<ResolvedToken>} [$$source = {}] - The source object to create the ResolvedToken.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ID"] = "";
        }
        if (!("Type" in $$source)) {
            /**
             * @member
             * @type {TokenType}
             */
            this["Type"] = TokenType.$zero;
        }
        if (!("States" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: Literal }}
             */
            this["States"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResolvedToken instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ResolvedToken}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("States" in $$parsedSource) {
            $$parsedSource["States"] = $$createField2_0($$parsedSource["States"]);
        }
        return new ResolvedToken(/** @type {Partial<ResolvedToken>} */($$parsedSource));
    }
}

export class ShadowLayer {
    /**
     * Creates a new ShadowLayer instance.
     * @param {Partial<ShadowLayer>} [$$source = {}] - The source object to create the ShadowLayer.
     */
    constructor($$source = {}) {
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }
        if (!("blur" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["blur"] = 0;
        }
        if (!("spread" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["spread"] = 0;
        }
        if (!("inset" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["inset"] = false;
        }
        if (!("color" in $$source)) {
            /**
             * @member
             * @type {TokenValue}
             */
            this["color"] = (new TokenValue());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShadowLayer instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ShadowLayer}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("color" in $$parsedSource) {
            $$parsedSource["color"] = $$createField5_0($$parsedSource["color"]);
        }
        return new ShadowLayer(/** @type {Partial<ShadowLayer>} */($$parsedSource));
    }
}

export class Theme {
    /**
     * Creates a new Theme instance.
     * @param {Partial<Theme>} [$$source = {}] - The source object to create the Theme.
     */
    constructor($$source = {}) {
        if (!("meta" in $$source)) {
            /**
             * @member
             * @type {ThemeMeta}
             */
            this["meta"] = (new ThemeMeta());
        }
        if (!("tokens" in $$source)) {
            /**
             * @member
             * @type {Token[]}
             */
            this["tokens"] = [];
        }
        if (!("components" in $$source)) {
            /**
             * @member
             * @type {ComponentStyle[]}
             */
            this["components"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Theme instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Theme}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType17;
        const $$createField1_0 = $$createType19;
        const $$createField2_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("meta" in $$parsedSource) {
            $$parsedSource["meta"] = $$createField0_0($$parsedSource["meta"]);
        }
        if ("tokens" in $$parsedSource) {
            $$parsedSource["tokens"] = $$createField1_0($$parsedSource["tokens"]);
        }
        if ("components" in $$parsedSource) {
            $$parsedSource["components"] = $$createField2_0($$parsedSource["components"]);
        }
        return new Theme(/** @type {Partial<Theme>} */($$parsedSource));
    }
}

/**
 * @typedef {any} ThemeError
 */

export class ThemeMeta {
    /**
     * Creates a new ThemeMeta instance.
     * @param {Partial<ThemeMeta>} [$$source = {}] - The source object to create the ThemeMeta.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["version"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeMeta instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ThemeMeta}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThemeMeta(/** @type {Partial<ThemeMeta>} */($$parsedSource));
    }
}

export class Token {
    /**
     * Creates a new Token instance.
     * @param {Partial<Token>} [$$source = {}] - The source object to create the Token.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {TokenType}
             */
            this["type"] = TokenType.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {TokenValue | undefined}
             */
            this["value"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: TokenValue } | undefined}
             */
            this["states"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {TokenMeta | null | undefined}
             */
            this["meta"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Token instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Token}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType23;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("value" in $$parsedSource) {
            $$parsedSource["value"] = $$createField2_0($$parsedSource["value"]);
        }
        if ("states" in $$parsedSource) {
            $$parsedSource["states"] = $$createField3_0($$parsedSource["states"]);
        }
        if ("meta" in $$parsedSource) {
            $$parsedSource["meta"] = $$createField4_0($$parsedSource["meta"]);
        }
        return new Token(/** @type {Partial<Token>} */($$parsedSource));
    }
}

export class TokenMeta {
    /**
     * Creates a new TokenMeta instance.
     * @param {Partial<TokenMeta>} [$$source = {}] - The source object to create the TokenMeta.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["label"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["group"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["order"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TokenMeta instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TokenMeta}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TokenMeta(/** @type {Partial<TokenMeta>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const TokenType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    TokenColor: "color",
    TokenNumber: "number",
    TokenSpacing: "spacing",
    TokenRadius: "radius",
    TokenShadow: "shadow",
    TokenGradient: "gradient",
};

export class TokenValue {
    /**
     * Creates a new TokenValue instance.
     * @param {Partial<TokenValue>} [$$source = {}] - The source object to create the TokenValue.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Literal | null | undefined}
             */
            this["literal"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Ref | null | undefined}
             */
            this["ref"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Derived | null | undefined}
             */
            this["derived"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TokenValue instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TokenValue}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType24;
        const $$createField1_0 = $$createType26;
        const $$createField2_0 = $$createType28;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("literal" in $$parsedSource) {
            $$parsedSource["literal"] = $$createField0_0($$parsedSource["literal"]);
        }
        if ("ref" in $$parsedSource) {
            $$parsedSource["ref"] = $$createField1_0($$parsedSource["ref"]);
        }
        if ("derived" in $$parsedSource) {
            $$parsedSource["derived"] = $$createField2_0($$parsedSource["derived"]);
        }
        return new TokenValue(/** @type {Partial<TokenValue>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = TokenValue.createFrom;
const $$createType1 = $Create.Map($Create.Any, $$createType0);
const $$createType2 = $Create.Map($Create.Any, $$createType1);
const $$createType3 = GradientStop.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = ColorLiteral.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = NumberLiteral.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = ShadowLayer.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = GradientLiteral.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = ResolvedToken.createFrom;
const $$createType14 = $Create.Map($Create.Any, $$createType13);
const $$createType15 = Literal.createFrom;
const $$createType16 = $Create.Map($Create.Any, $$createType15);
const $$createType17 = ThemeMeta.createFrom;
const $$createType18 = Token.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = ComponentStyle.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = TokenMeta.createFrom;
const $$createType23 = $Create.Nullable($$createType22);
const $$createType24 = $Create.Nullable($$createType15);
const $$createType25 = Ref.createFrom;
const $$createType26 = $Create.Nullable($$createType25);
const $$createType27 = Derived.createFrom;
const $$createType28 = $Create.Nullable($$createType27);
