// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} name
 * @param {string} base
 * @returns {$CancellablePromise<void>}
 */
export function CreateTheme(name, base) {
    return $Call.ByID(3008312038, name, base);
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function GetThemes() {
    return $Call.ByID(2795884557).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<$models.Theme>}
 */
export function LoadRawTheme(name) {
    return $Call.ByID(3297331294, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<[$models.ResolvedTheme, $models.ThemeError[]]>}
 */
export function LoadResolvedTheme(name) {
    return $Call.ByID(3319198394, name).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType2($result[0]);
        $result[1] = $$createType3($result[1]);
        return $result;
    }));
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<[string, $models.ThemeError[]]>}
 */
export function LoadThemeCSS(name) {
    return $Call.ByID(2475938385, name).then(/** @type {($result: any) => any} */(($result) => {
        $result[1] = $$createType3($result[1]);
        return $result;
    }));
}

/**
 * @param {string} name
 * @param {$models.Theme} theme
 * @returns {$CancellablePromise<void>}
 */
export function SaveTheme(name, theme) {
    return $Call.ByID(3187247329, name, theme);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.Theme.createFrom;
const $$createType2 = $models.ResolvedTheme.createFrom;
const $$createType3 = $Create.Array($Create.Any);
