// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsLanguageEditorOpen() {
    return $Call.ByID(3738628032);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsThemeEditorOpen() {
    return $Call.ByID(3774607593);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenLanguageEditor() {
    return $Call.ByID(3789064376);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenThemeEditor() {
    return $Call.ByID(2471180485);
}
