// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class DiscordInvite {
    /**
     * Creates a new DiscordInvite instance.
     * @param {Partial<DiscordInvite>} [$$source = {}] - The source object to create the DiscordInvite.
     */
    constructor($$source = {}) {
        if (!("approximate_presence_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["approximate_presence_count"] = 0;
        }
        if (!("approximate_member_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["approximate_member_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiscordInvite instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiscordInvite}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiscordInvite(/** @type {Partial<DiscordInvite>} */($$parsedSource));
    }
}
