// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Запуск игры с аргументами
 * @param {string} path
 * @param {string[]} args
 * @returns {$CancellablePromise<void>}
 */
export function LaunchGameExe(path, ...args) {
    return $Call.ByID(270520792, path, args);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenFile(path) {
    return $Call.ByID(3579167675, path);
}

/**
 * Открыть папку в проводнике
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenFolderInExplorer(path) {
    return $Call.ByID(3950432153, path);
}
