// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetAppVersion() {
    return $Call.ByID(287003546);
}

/**
 * @param {string} inviteCode
 * @returns {$CancellablePromise<$models.DiscordInvite | null>}
 */
export function GetDiscordStats(inviteCode) {
    return $Call.ByID(1690288880, inviteCode).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Запуск игры с аргументами
 * @param {string} path
 * @param {string[]} args
 * @returns {$CancellablePromise<void>}
 */
export function LaunchGameExe(path, ...args) {
    return $Call.ByID(270520792, path, args);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenDevTools() {
    return $Call.ByID(3153944503);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenFile(path) {
    return $Call.ByID(3579167675, path);
}

/**
 * Открыть папку в проводнике
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenFolderInExplorer(path) {
    return $Call.ByID(3950432153, path);
}

/**
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function OpenURL(url) {
    return $Call.ByID(3202016086, url);
}

// Private type creation functions
const $$createType0 = $models.DiscordInvite.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
