// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as version$0 from "../version/models.js";

export class ComponentUpdate {
    /**
     * Creates a new ComponentUpdate instance.
     * @param {Partial<ComponentUpdate>} [$$source = {}] - The source object to create the ComponentUpdate.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * "theme" or "locale"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("changelog" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["changelog"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ComponentUpdate instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ComponentUpdate}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ComponentUpdate(/** @type {Partial<ComponentUpdate>} */($$parsedSource));
    }
}

/**
 * ComponentVersions matches the structure of manifest.json
 */
export class ComponentVersions {
    /**
     * Creates a new ComponentVersions instance.
     * @param {Partial<ComponentVersions>} [$$source = {}] - The source object to create the ComponentVersions.
     */
    constructor($$source = {}) {
        if (!("app_version" in $$source)) {
            /**
             * @member
             * @type {version$0.ComponentInfo}
             */
            this["app_version"] = (new version$0.ComponentInfo());
        }
        if (!("themes" in $$source)) {
            /**
             * @member
             * @type {{ [_: string]: version$0.ComponentInfo }}
             */
            this["themes"] = {};
        }
        if (!("locales" in $$source)) {
            /**
             * @member
             * @type {{ [_: string]: version$0.ComponentInfo }}
             */
            this["locales"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ComponentVersions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ComponentVersions}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("app_version" in $$parsedSource) {
            $$parsedSource["app_version"] = $$createField0_0($$parsedSource["app_version"]);
        }
        if ("themes" in $$parsedSource) {
            $$parsedSource["themes"] = $$createField1_0($$parsedSource["themes"]);
        }
        if ("locales" in $$parsedSource) {
            $$parsedSource["locales"] = $$createField2_0($$parsedSource["locales"]);
        }
        return new ComponentVersions(/** @type {Partial<ComponentVersions>} */($$parsedSource));
    }
}

export class UpdateCheckResult {
    /**
     * Creates a new UpdateCheckResult instance.
     * @param {Partial<UpdateCheckResult>} [$$source = {}] - The source object to create the UpdateCheckResult.
     */
    constructor($$source = {}) {
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateCheckResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateCheckResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateCheckResult(/** @type {Partial<UpdateCheckResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = version$0.ComponentInfo.createFrom;
const $$createType1 = $Create.Map($Create.Any, $$createType0);
