// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckForComponentUpdates fetches manifest and compares with local versions.
 * @returns {$CancellablePromise<$models.ComponentUpdate[]>}
 */
export function CheckForComponentUpdates() {
    return $Call.ByID(3573180877).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CheckForUpdates checks if a new app version is available on GitHub.
 * @returns {$CancellablePromise<$models.UpdateCheckResult>}
 */
export function CheckForUpdates() {
    return $Call.ByID(942478956).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * DoUpdate downloads a new executable side-by-side and marks update as ready.
 * @param {string} targetVersion
 * @returns {$CancellablePromise<void>}
 */
export function DoUpdate(targetVersion) {
    return $Call.ByID(1725521721, targetVersion);
}

/**
 * LoadLocalVersions loads versions from manifest.json in AppData.
 * @returns {$CancellablePromise<$models.ComponentVersions>}
 */
export function LoadLocalVersions() {
    return $Call.ByID(333119061).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * RestartApp launches the new executable and quits current process.
 * @returns {$CancellablePromise<void>}
 */
export function RestartApp() {
    return $Call.ByID(4288405115);
}

/**
 * SaveLocalVersions saves versions to manifest.json in AppData.
 * @param {$models.ComponentVersions} versions
 * @returns {$CancellablePromise<void>}
 */
export function SaveLocalVersions(versions) {
    return $Call.ByID(1019144030, versions);
}

/**
 * UpdateComponent downloads component file and updates local component versions.
 * @param {$models.ComponentUpdate} update
 * @returns {$CancellablePromise<void>}
 */
export function UpdateComponent(update) {
    return $Call.ByID(2462522599, update);
}

// Private type creation functions
const $$createType0 = $models.ComponentUpdate.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.UpdateCheckResult.createFrom;
const $$createType3 = $models.ComponentVersions.createFrom;
