// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MapDownloader соответствует MapDownloader из Rust
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DownloadMapCommand — Wails-команда для загрузки карты
 * @param {$models.MapInfo} mapInfo
 * @returns {$CancellablePromise<$models.MapMetadata>}
 */
export function DownloadMap(mapInfo) {
    return $Call.ByID(1528650682, mapInfo).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetChangelogCommand — Wails-команда для получения списка изменений
 * @param {string} version
 * @returns {$CancellablePromise<string>}
 */
export function GetChangelog(version) {
    return $Call.ByID(459703602, version);
}

/**
 * GetMapInfoCommand — Wails-команда для получения информации о карте
 * @returns {$CancellablePromise<$models.MapInfo>}
 */
export function GetMapInfo() {
    return $Call.ByID(192268846).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.MapMetadata.createFrom;
const $$createType1 = $models.MapInfo.createFrom;
