// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * MapInfo соответствует MapInfo из Rust
 */
export class MapInfo {
    /**
     * Creates a new MapInfo instance.
     * @param {Partial<MapInfo>} [$$source = {}] - The source object to create the MapInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("download_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["download_url"] = "";
        }
        if (!("date" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["date"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * int64 для размера
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("save_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["save_path"] = "";
        }
        if (!("is_downloaded" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_downloaded"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MapInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MapInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MapInfo(/** @type {Partial<MapInfo>} */($$parsedSource));
    }
}

/**
 * MapMetadata соответствует MapMetadata из Rust
 */
export class MapMetadata {
    /**
     * Creates a new MapMetadata instance.
     * @param {Partial<MapMetadata>} [$$source = {}] - The source object to create the MapMetadata.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("is_downloaded" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_downloaded"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MapMetadata instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MapMetadata}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MapMetadata(/** @type {Partial<MapMetadata>} */($$parsedSource));
    }
}
