// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppSettings is a Wails service exposing settings APIs to frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetDefaultSettings returns the default settings.
 * @returns {$CancellablePromise<$models.Settings>}
 */
export function GetDefaultSettings() {
    return $Call.ByID(3198308038).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetOption returns option value by key.
 * @param {string} key
 * @returns {$CancellablePromise<any>}
 */
export function GetOption(key) {
    return $Call.ByID(871403771, key);
}

/**
 * GetSettings returns current settings.
 * @returns {$CancellablePromise<$models.Settings>}
 */
export function GetSettings() {
    return $Call.ByID(3749339043).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * UpdateSettings validates and persists settings.
 * @param {$models.Settings} newSettings
 * @returns {$CancellablePromise<$models.Settings>}
 */
export function UpdateSettings(newSettings) {
    return $Call.ByID(4245491006, newSettings).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.Settings.createFrom;
