// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * CheckAndFindPaths scans registry + disks and returns unique sorted install paths.
 * @returns {$CancellablePromise<string[]>}
 */
export function CheckAndFindPaths() {
    return $Call.ByID(960453642).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function FindConfigOrExeParallel() {
    return $Call.ByID(604715575).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
