// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * ApplyChangesToConfig — применяет изменения из diff к текущему конфигу в памяти и сохраняет его.
 * @param {{ [_: string]: { [_: string]: { [_: string]: string } } }} diff
 * @returns {$CancellablePromise<void>}
 */
export function ApplyChangesToConfig(diff) {
    return $Call.ByID(2148346302, diff);
}

/**
 * CheckConfigDiff сравнивает текущий конфиг в памяти с тем, что на диске,
 * возвращает map[section]map[key]value только с изменёнными значениями
 * @returns {$CancellablePromise<{ [_: string]: { [_: string]: { [_: string]: string } } }>}
 */
export function CheckConfigDiff() {
    return $Call.ByID(3404297753).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * DiscardExternalChanges — перезаписывает конфиг на диске текущим состоянием из памяти.
 * Это отменяет любые внешние изменения, применяя нашу in-memory версию.
 * @returns {$CancellablePromise<void>}
 */
export function DiscardExternalChanges() {
    return $Call.ByID(1771186194);
}

/**
 * Получить значение
 * @param {string} section
 * @param {string} option
 * @returns {$CancellablePromise<string>}
 */
export function GetConfigValue(section, option) {
    return $Call.ByID(2375517143, section, option);
}

/**
 * Получить значение как Hotkey
 * @param {string} section
 * @param {string} option
 * @returns {$CancellablePromise<string>}
 */
export function GetHotkeyValue(section, option) {
    return $Call.ByID(1018981739, section, option);
}

/**
 * Проверить наличие
 * @returns {$CancellablePromise<boolean>}
 */
export function IsConfigAvailable() {
    return $Call.ByID(1220983505);
}

/**
 * Загрузить конфиг
 * @param {string} configPath
 * @returns {$CancellablePromise<{ [_: string]: { [_: string]: string } }>}
 */
export function LoadConfig(configPath) {
    return $Call.ByID(680888446, configPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Установить значение
 * @param {string} section
 * @param {string} option
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function SetConfigValue(section, option, value) {
    return $Call.ByID(3655177611, section, option, value);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Map($Create.Any, $$createType0);
const $$createType2 = $Create.Map($Create.Any, $$createType1);
