// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplyChangesToConfig applies external changes into in-memory config and saves it.
 * @param {$models.SectionDiff[]} diff
 * @returns {$CancellablePromise<void>}
 */
export function ApplyChangesToConfig(diff) {
    return $Call.ByID(2148346302, diff);
}

/**
 * CheckConfigDiff compares the current in-memory config with the on-disk file
 * and returns only externally changed sections/keys.
 * @returns {$CancellablePromise<$models.SectionDiff[]>}
 */
export function CheckConfigDiff() {
    return $Call.ByID(3404297753).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * DiscardExternalChanges overwrites the on-disk config with current in-memory state.
 * @returns {$CancellablePromise<void>}
 */
export function DiscardExternalChanges() {
    return $Call.ByID(1771186194);
}

/**
 * Получить значение
 * @param {string} section
 * @param {string} option
 * @returns {$CancellablePromise<string>}
 */
export function GetConfigValue(section, option) {
    return $Call.ByID(2375517143, section, option);
}

/**
 * GetConfigValueStrict returns config value with strict error semantics.
 * @param {string} section
 * @param {string} option
 * @returns {$CancellablePromise<string>}
 */
export function GetConfigValueStrict(section, option) {
    return $Call.ByID(82077650, section, option);
}

/**
 * Получить значение как Hotkey
 * @param {string} section
 * @param {string} option
 * @returns {$CancellablePromise<string>}
 */
export function GetHotkeyValue(section, option) {
    return $Call.ByID(1018981739, section, option);
}

/**
 * Проверить наличие
 * @returns {$CancellablePromise<boolean>}
 */
export function IsConfigAvailable() {
    return $Call.ByID(1220983505);
}

/**
 * Загрузить конфиг
 * @param {string} configPath
 * @returns {$CancellablePromise<{ [_ in string]?: { [_ in string]?: string } }>}
 */
export function LoadConfig(configPath) {
    return $Call.ByID(680888446, configPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * Установить значение
 * @param {string} section
 * @param {string} option
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function SetConfigValue(section, option, value) {
    return $Call.ByID(3655177611, section, option, value);
}

// Private type creation functions
const $$createType0 = $models.SectionDiff.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Map($Create.Any, $$createType2);
