// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * @readonly
 * @enum {string}
 */
export const DiffStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    DiffStatusAdded: "added",
    DiffStatusModified: "modified",
    DiffStatusDeleted: "deleted",
};

export class KeyDiff {
    /**
     * Creates a new KeyDiff instance.
     * @param {Partial<KeyDiff>} [$$source = {}] - The source object to create the KeyDiff.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("old" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["old"] = "";
        }
        if (!("new" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["new"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {DiffStatus}
             */
            this["status"] = DiffStatus.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KeyDiff instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KeyDiff}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KeyDiff(/** @type {Partial<KeyDiff>} */($$parsedSource));
    }
}

export class SectionDiff {
    /**
     * Creates a new SectionDiff instance.
     * @param {Partial<SectionDiff>} [$$source = {}] - The source object to create the SectionDiff.
     */
    constructor($$source = {}) {
        if (!("section" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["section"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {DiffStatus}
             */
            this["status"] = DiffStatus.$zero;
        }
        if (!("keys" in $$source)) {
            /**
             * @member
             * @type {KeyDiff[]}
             */
            this["keys"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SectionDiff instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SectionDiff}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("keys" in $$parsedSource) {
            $$parsedSource["keys"] = $$createField2_0($$parsedSource["keys"]);
        }
        return new SectionDiff(/** @type {Partial<SectionDiff>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = KeyDiff.createFrom;
const $$createType1 = $Create.Array($$createType0);
