// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    ComponentInfo
} from "./models.js";

import * as $models from "./models.js";

/**
 * @typedef {$models.MultiLineString} MultiLineString
 */
