// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ComponentInfo {
    /**
     * Creates a new ComponentInfo instance.
     * @param {Partial<ComponentInfo>} [$$source = {}] - The source object to create the ComponentInfo.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {MultiLineString | undefined}
             */
            this["changelog"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ComponentInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ComponentInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ComponentInfo(/** @type {Partial<ComponentInfo>} */($$parsedSource));
    }
}

/**
 * @typedef {string} MultiLineString
 */
