// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * I18N handles internationalization
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetCurrentLanguage returns the current language from settings
 * @returns {$CancellablePromise<string>}
 */
export function GetCurrentLanguage() {
    return $Call.ByID(323253130);
}

/**
 * GetLanguages returns available languages
 * @returns {$CancellablePromise<{ [_: string]: string }[]>}
 */
export function GetLanguages() {
    return $Call.ByID(1746410022).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetTranslations returns translations for a specific language
 * @param {string} langCode
 * @returns {$CancellablePromise<{ [_: string]: string }>}
 */
export function GetTranslations(langCode) {
    return $Call.ByID(3972488175, langCode).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetTranslationsCurrent returns translations for the current language
 * @returns {$CancellablePromise<{ [_: string]: string }>}
 */
export function GetTranslationsCurrent() {
    return $Call.ByID(1150385824).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SwitchLanguage changes the language in settings
 * @param {string} newLang
 * @returns {$CancellablePromise<void>}
 */
export function SwitchLanguage(newLang) {
    return $Call.ByID(3569868495, newLang);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($$createType0);
